
rename_pcd_output = {
    'Report_End':'report_period_end',
    'REGION_CODE':'region_code',
    'REGION_NAME':'region_name',
    'SUB_ICB_CODE':'sub_ICB_location_code',
    'SUB_ICB_NAME':'sub_ICB_location_name',
    'PRACTICE_CODE':'practice_code',
    'PRACTICE_NAME':'practice_name',
    'Supplier':'system_supplier',
    'Total_Patients':'patient_list_size',
    'FIELD_KEY_21':'Sys_Appts_Enbld',
    'FIELD_KEY_32':'Pat_Appts_Enbld',
    'online_book_cancel_count':'Pat_Appts_Use',
    'FIELD_KEY_22':'Sys_Presc_Enbld',
    'FIELD_KEY_34':'Pat_Presc_Enbld',
    'FIELD_KEY_51':'Pat_Presc_Use',
    'FIELD_KEY_61':'Sys_DetCodeRec_Enbld',
    'FIELD_KEY_62':'Pat_DetCodeRec_Enbld',
    'FIELD_KEY_63':'Pat_DetCodeRec_Use',
    'FIELD_KEY_30':'Total_Pat_Enbld',
    'FIELD_KEY_31':'New_Pat_Enbld',
    'FIELD_KEY_47':'Total_Use',
    }

rename_benefits_output = {
    'Report_End':'report_period_end',
    'Supplier':'supplier',
    'FIELD_KEY_8':'appointment_cancelled_trans_count',
    'FIELD_KEY_10':'appointment_cancelled_ooh_online_trans_count',
    'FIELD_KEY_11':'appointment_available_count',
    'FIELD_KEY_12':'appointment_available_online_count',
    'FIELD_KEY_13':'appointment_scheduled_count',
    'FIELD_KEY_14':'appointment_dna_appt_count',
    'FIELD_KEY_15':'appointment_dna_online_appt_count',
    'FIELD_KEY_16':'prescriptions_ordered_trans_count',
    'FIELD_KEY_17':'items_ordered_total_count',
    'FIELD_KEY_30':'online_patient_count',
    'FIELD_KEY_31':'new_online_patient_count',
    'FIELD_KEY_40':'online_patient_record_view_count',
    'FIELD_KEY_42':'online_patient_letter_view_count',
    'FIELD_KEY_44':'online_record_letter_view_count',
    'FIELD_KEY_45':'online_patient_test_result_view_count',
    'FIELD_KEY_47':'total_online_transactions_count',
    'FIELD_KEY_48':'unique_online_patient_record_trans_count',
    'FIELD_KEY_49':'appointment_scheduled_online_trans_count',
    'FIELD_KEY_50':'appointment_cancelled_online_trans_count',
    'FIELD_KEY_51':'prescription_online_trans_count',
    'FIELD_KEY_52':'comms_online_patient_count',
    'FIELD_KEY_53':'comms_online_clinician_count',
    'FIELD_KEY_54':'online_record_view_count',
    'FIELD_KEY_56':'online_record_test_result_view_count',
    'FIELD_KEY_57':'update_demographics_online_trans_count',
    }

rename_pbi_output = {
    'REGION_CODE':'RegionCode',
    'REGION_NAME':'RegionName',
    'PRACTICE_CODE':'GPPracticeCode',
    'PRACTICE_NAME':'GPPracticeName',
    'Report_End':'report_period_end',
    'Total_Patients':'NoPatients',
    'FIELD_KEY_21':'APPT_FUNC_FLAG',
    'FIELD_KEY_22':'PRESC_FUNC_FLAG',
    'FIELD_KEY_61':'DCR_FUNC_FLAG',
    'FIELD_KEY_32':'Pat_Appts_Enbld',
    'online_book_cancel_count':'Pat_Appts_Use',
    'FIELD_KEY_30':'Total_Pat_Enabled',
    'FIELD_KEY_34':'Pat_Presc_Enbld',
    'FIELD_KEY_51':'Pat_Presc_Use',
    'FIELD_KEY_62':'Pat_DetCodeRec_Enbld',
    'FIELD_KEY_63':'Pat_DetCodeRec_Use'
    }

nhs_regions = [
    ("Y54", "NORTH OF ENGLAND COMMISSIONING REGION"),
    ("Y55", "MIDLANDS AND EAST OF ENGLAND COMMISSIONING REGION"),
    ("Y56", "LONDON COMMISSIONING REGION"),
    ("Y57", "SOUTH OF ENGLAND COMMISSIONING REGION"),
    ("Y58", "SOUTH WEST COMMISSIONING REGION"),
    ("Y59", "SOUTH EAST COMMISSIONING REGION"),
    ("Y60", "MIDLANDS COMMISSIONING REGION"),
    ("Y61", "EAST OF ENGLAND COMMISSIONING REGION"),
    ("Y62", "NORTH WEST COMMISSIONING REGION"),
    ("Y63", "NORTH EAST AND YORKSHIRE COMMISSIONING REGION")
    ]